---
# tasks file for ansible-windows-exporter

- name: Include asserts
  ansible.builtin.include_tasks:
    file: asserts.yml
  tags:
    - always

- name: Check if windows exporter is already installed
  ansible.windows.win_service:
    name: windows_exporter
  register: windows_exporter_service
  ignore_errors: true

- name: Get installed windows exporter version
  when: windows_exporter_service.exists
  block:
    - name: Get installed windows exporter version | Run command
      ansible.windows.win_shell: '.\windows_exporter.exe --version'
      args:
        chdir: "{{ windows_exporter_install_path }}"
      changed_when: false
      check_mode: false
      register: exporter_output

    - name: Get installed windows exporter version | Set version fact
      ansible.builtin.set_fact:
        installed_exporter_version: "{{ exporter_output.stderr | regex_search('\\d+\\.\\d+\\.\\d+') }}"

- name: Print exporter version identified
  ansible.builtin.debug:
    msg: >-
      {% if windows_exporter_version == installed_exporter_version %}
      Windows Exporter Version {{ installed_exporter_version }} is already installed!
      {% else %}
      Windows Exporter Version {{ installed_exporter_version }} will be redeployed with {{ windows_exporter_version }}
      {% endif %}
  when:
    - windows_exporter_service.exists
    - installed_exporter_version is defined

- name: Include Uninstall
  ansible.builtin.include_tasks:
    file: uninstall.yml
    apply:
      vars:
        windows_exporter_version: "{{ installed_exporter_version }}"
  when:
    - windows_exporter_service.exists
    - windows_exporter_version != installed_exporter_version
    - windows_exporter_create_uninstall

- name: Include Install
  ansible.builtin.include_tasks:
    file: install.yml
  when: (not windows_exporter_service.exists or windows_exporter_version != installed_exporter_version)

- name: Include Configure
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Check if Windows Exporter responding to requests
  ansible.windows.win_uri:
    url: "http://{{ ansible_host }}:{{ windows_exporter_port }}/metrics"
    return_content: false
    status_code: 200
  when: windows_exporter_start_mode not in ['disabled', 'manual']
